name: Javadoc CI

on:
  push:
    branches:
      - master

permissions: 
  contents: write
jobs:
  javadoc:
    if: ${{ github.repository_owner == 'tr7zw' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8
    - name: Build with Maven
      run: mvn package
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        clean: false
        folder: item-nbt-api/target/apidocs
        target-folder: v2-api
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        clean: false
        folder: item-nbt-plugin/target/apidocs
        target-folder: v2-plugin
